name: queen_ui
description: collection of ui pre built components to save you the boilerplate
version: 0.0.1+1
author: AHMED MASOUD
homepage: https://github.com/maxzod/queen_ui
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  lint: ^1.5.3
